[project]
name = "agentic-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vinod Gharde", email = "vinodgharde1989@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
agentic-chatbot = "agentic_chatbot:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
